CREATE ROLE ROL_ADMIN_ARALIAS;
CREATE ROLE ROL_SEGURIDAD;
CREATE ROLE ROL_ADMINISTRACION;
CREATE ROLE ROL_CONSULTA;

CREATE USER ADMIN_ARALIAS
    IDENTIFIED BY "Lenguajes_12345678";
    
    ALTER USER ADMIN_ARALIAS QUOTA UNLIMITED ON DATA;

CREATE USER SEGURIDAD
    IDENTIFIED BY "Lenguajes_12345678";

CREATE USER ADMINISTRADOR
    IDENTIFIED BY "Lenguajes_12345678";

CREATE USER AUDITOR
    IDENTIFIED BY "Lenguajes_12345678";

GRANT CREATE SESSION   TO ROL_ADMIN_ARALIAS;
GRANT CREATE TABLE     TO ROL_ADMIN_ARALIAS;
GRANT CREATE VIEW      TO ROL_ADMIN_ARALIAS;
GRANT CREATE MATERIALIZED VIEW TO ROL_ADMIN_ARALIAS;
GRANT CREATE SEQUENCE  TO ROL_ADMIN_ARALIAS;
GRANT CREATE PROCEDURE TO ROL_ADMIN_ARALIAS;
GRANT CREATE TRIGGER   TO ROL_ADMIN_ARALIAS;
GRANT CREATE SYNONYM   TO ROL_ADMIN_ARALIAS;

GRANT CREATE SESSION TO ROL_SEGURIDAD;
GRANT CREATE SESSION TO ROL_ADMINISTRACION;
GRANT CREATE SESSION TO ROL_CONSULTA;

GRANT ROL_ADMIN_ARALIAS TO ADMIN_ARALIAS;
GRANT ROL_SEGURIDAD TO SEGURIDAD;
GRANT ROL_ADMINISTRACION TO ADMINISTRADOR;
GRANT ROL_CONSULTA TO AUDITOR;

GRANT ALL ON ADMIN_ARALIAS.FIDE_ESTADOS_TB TO ROL_ADMIN_ARALIAS;
GRANT ALL ON ADMIN_ARALIAS.FIDE_ROLES_TB TO ROL_ADMIN_ARALIAS;
GRANT ALL ON ADMIN_ARALIAS.FIDE_TIPOS_PAGO_TB TO ROL_ADMIN_ARALIAS;
GRANT ALL ON ADMIN_ARALIAS.FIDE_FORMAS_PAGOS_TB TO ROL_ADMIN_ARALIAS;
GRANT ALL ON ADMIN_ARALIAS.FIDE_HORARIOS_TURNOS_TB TO ROL_ADMIN_ARALIAS;
GRANT ALL ON ADMIN_ARALIAS.FIDE_FECHAS_TURNOS_TB TO ROL_ADMIN_ARALIAS;
GRANT ALL ON ADMIN_ARALIAS.FIDE_TIPOS_ESPACIOS_TB TO ROL_ADMIN_ARALIAS;
GRANT ALL ON ADMIN_ARALIAS.FIDE_TIPOS_EVENTOS_TB TO ROL_ADMIN_ARALIAS;
GRANT ALL ON ADMIN_ARALIAS.FIDE_TIPOS_SERVICIOS_TB TO ROL_ADMIN_ARALIAS;
GRANT ALL ON ADMIN_ARALIAS.FIDE_PERSONAS_TB TO ROL_ADMIN_ARALIAS;
GRANT ALL ON ADMIN_ARALIAS.FIDE_TELEFONOS_TB TO ROL_ADMIN_ARALIAS;
GRANT ALL ON ADMIN_ARALIAS.FIDE_CORREOS_TB TO ROL_ADMIN_ARALIAS;
GRANT ALL ON ADMIN_ARALIAS.FIDE_RESIDENCIAS_TB TO ROL_ADMIN_ARALIAS;
GRANT ALL ON ADMIN_ARALIAS.FIDE_RESIDENTES_TB TO ROL_ADMIN_ARALIAS;
GRANT ALL ON ADMIN_ARALIAS.FIDE_EVENTOS_TB TO ROL_ADMIN_ARALIAS;
GRANT ALL ON ADMIN_ARALIAS.FIDE_VEHICULOS_TB TO ROL_ADMIN_ARALIAS;
GRANT ALL ON ADMIN_ARALIAS.FIDE_SERVICIOS_TB TO ROL_ADMIN_ARALIAS;
GRANT ALL ON ADMIN_ARALIAS.FIDE_FACTURAS_TB TO ROL_ADMIN_ARALIAS;
GRANT ALL ON ADMIN_ARALIAS.FIDE_CONSULTAS_TB TO ROL_ADMIN_ARALIAS;
GRANT ALL ON ADMIN_ARALIAS.FIDE_REPORTES_TB TO ROL_ADMIN_ARALIAS;
GRANT ALL ON ADMIN_ARALIAS.FIDE_SALARIOS_TB TO ROL_ADMIN_ARALIAS;
GRANT ALL ON ADMIN_ARALIAS.FIDE_PAQUETES_TB TO ROL_ADMIN_ARALIAS;
GRANT ALL ON ADMIN_ARALIAS.FIDE_TURNOS_TB TO ROL_ADMIN_ARALIAS;
GRANT ALL ON ADMIN_ARALIAS.FIDE_VISITAS_TB TO ROL_ADMIN_ARALIAS;
GRANT ALL ON ADMIN_ARALIAS.FIDE_PERSONAS_SERVICIOS_TB TO ROL_ADMIN_ARALIAS;
GRANT ALL ON ADMIN_ARALIAS.FIDE_RESUMENES_TURNOS_TB TO ROL_ADMIN_ARALIAS;

GRANT SELECT ON ADMIN_ARALIAS.FIDE_ESTADOS_TB TO ROL_SEGURIDAD;
GRANT SELECT ON ADMIN_ARALIAS.FIDE_ROLES_TB TO ROL_SEGURIDAD;
GRANT SELECT ON ADMIN_ARALIAS.FIDE_TIPOS_ESPACIOS_TB TO ROL_SEGURIDAD;
GRANT SELECT ON ADMIN_ARALIAS.FIDE_TIPOS_EVENTOS_TB TO ROL_SEGURIDAD;
GRANT SELECT ON ADMIN_ARALIAS.FIDE_TIPOS_SERVICIOS_TB TO ROL_SEGURIDAD;
GRANT SELECT ON ADMIN_ARALIAS.FIDE_HORARIOS_TURNOS_TB TO ROL_SEGURIDAD;
GRANT SELECT ON ADMIN_ARALIAS.FIDE_FECHAS_TURNOS_TB TO ROL_SEGURIDAD;
GRANT SELECT, INSERT ON ADMIN_ARALIAS.FIDE_PERSONAS_TB TO ROL_SEGURIDAD;
GRANT SELECT ON ADMIN_ARALIAS.FIDE_TELEFONOS_TB TO ROL_SEGURIDAD;
GRANT SELECT ON ADMIN_ARALIAS.FIDE_CORREOS_TB TO ROL_SEGURIDAD;
GRANT SELECT ON ADMIN_ARALIAS.FIDE_RESIDENCIAS_TB TO ROL_SEGURIDAD;
GRANT SELECT ON ADMIN_ARALIAS.FIDE_RESIDENTES_TB TO ROL_SEGURIDAD;
GRANT SELECT, INSERT, UPDATE ON ADMIN_ARALIAS.FIDE_VISITAS_TB TO ROL_SEGURIDAD;
GRANT SELECT, INSERT ON ADMIN_ARALIAS.FIDE_VEHICULOS_TB TO ROL_SEGURIDAD;
GRANT SELECT, INSERT, UPDATE ON ADMIN_ARALIAS.FIDE_PAQUETES_TB  TO ROL_SEGURIDAD;
GRANT SELECT, INSERT ON ADMIN_ARALIAS.FIDE_EVENTOS_TB TO ROL_SEGURIDAD;
GRANT SELECT, INSERT ON ADMIN_ARALIAS.FIDE_TURNOS_TB TO ROL_SEGURIDAD;
GRANT SELECT, INSERT ON ADMIN_ARALIAS.FIDE_RESUMENES_TURNOS_TB TO ROL_SEGURIDAD;
GRANT SELECT, INSERT ON ADMIN_ARALIAS.FIDE_CONSULTAS_TB TO ROL_SEGURIDAD;
GRANT SELECT, INSERT ON ADMIN_ARALIAS.FIDE_REPORTES_TB TO ROL_SEGURIDAD;

GRANT SELECT ON ADMIN_ARALIAS.FIDE_ESTADOS_TB TO ROL_ADMINISTRACION;
GRANT SELECT, INSERT ON ADMIN_ARALIAS.FIDE_ROLES_TB TO ROL_ADMINISTRACION;
GRANT SELECT, INSERT ON ADMIN_ARALIAS.FIDE_TIPOS_PAGO_TB TO ROL_ADMINISTRACION;
GRANT SELECT, INSERT ON ADMIN_ARALIAS.FIDE_FORMAS_PAGOS_TB TO ROL_ADMINISTRACION;
GRANT SELECT, INSERT ON ADMIN_ARALIAS.FIDE_TIPOS_ESPACIOS_TB TO ROL_ADMINISTRACION;
GRANT SELECT, INSERT ON ADMIN_ARALIAS.FIDE_TIPOS_EVENTOS_TB TO ROL_ADMINISTRACION;
GRANT SELECT, INSERT ON ADMIN_ARALIAS.FIDE_TIPOS_SERVICIOS_TB TO ROL_ADMINISTRACION;
GRANT SELECT, INSERT ON ADMIN_ARALIAS.FIDE_HORARIOS_TURNOS_TB TO ROL_ADMINISTRACION;
GRANT SELECT, INSERT ON ADMIN_ARALIAS.FIDE_FECHAS_TURNOS_TB TO ROL_ADMINISTRACION;
GRANT SELECT, INSERT, UPDATE ON ADMIN_ARALIAS.FIDE_PERSONAS_TB TO ROL_ADMINISTRACION;
GRANT SELECT, INSERT, UPDATE ON ADMIN_ARALIAS.FIDE_TELEFONOS_TB TO ROL_ADMINISTRACION;
GRANT SELECT, INSERT, UPDATE ON ADMIN_ARALIAS.FIDE_CORREOS_TB TO ROL_ADMINISTRACION;
GRANT SELECT, INSERT, UPDATE ON ADMIN_ARALIAS.FIDE_RESIDENCIAS_TB TO ROL_ADMINISTRACION;
GRANT SELECT, INSERT, UPDATE ON ADMIN_ARALIAS.FIDE_RESIDENTES_TB TO ROL_ADMINISTRACION;
GRANT SELECT, INSERT, UPDATE ON ADMIN_ARALIAS.FIDE_FACTURAS_TB TO ROL_ADMINISTRACION;
GRANT SELECT ON ADMIN_ARALIAS.FIDE_SALARIOS_TB TO ROL_ADMINISTRACION;
GRANT SELECT, INSERT, UPDATE ON ADMIN_ARALIAS.FIDE_SERVICIOS_TB TO ROL_ADMINISTRACION;
GRANT SELECT, INSERT, UPDATE ON ADMIN_ARALIAS.FIDE_PERSONAS_SERVICIOS_TB TO ROL_ADMINISTRACION;
GRANT SELECT ON ADMIN_ARALIAS.FIDE_EVENTOS_TB TO ROL_ADMINISTRACION;
GRANT SELECT ON ADMIN_ARALIAS.FIDE_PAQUETES_TB TO ROL_ADMINISTRACION;
GRANT SELECT ON ADMIN_ARALIAS.FIDE_VISITAS_TB TO ROL_ADMINISTRACION;
GRANT SELECT ON ADMIN_ARALIAS.FIDE_VEHICULOS_TB TO ROL_ADMINISTRACION;
GRANT SELECT, INSERT, UPDATE ON ADMIN_ARALIAS.FIDE_TURNOS_TB TO ROL_ADMINISTRACION;
GRANT SELECT, INSERT, UPDATE ON ADMIN_ARALIAS.FIDE_RESUMENES_TURNOS_TB TO ROL_ADMINISTRACION;
GRANT SELECT, INSERT ON ADMIN_ARALIAS.FIDE_CONSULTAS_TB TO ROL_ADMINISTRACION;
GRANT SELECT, INSERT ON ADMIN_ARALIAS.FIDE_REPORTES_TB TO ROL_ADMINISTRACION;

GRANT SELECT ON ADMIN_ARALIAS.FIDE_ESTADOS_TB TO ROL_CONSULTA;
GRANT SELECT ON ADMIN_ARALIAS.FIDE_ROLES_TB TO ROL_CONSULTA;
GRANT SELECT ON ADMIN_ARALIAS.FIDE_TIPOS_PAGO_TB TO ROL_CONSULTA;
GRANT SELECT ON ADMIN_ARALIAS.FIDE_FORMAS_PAGOS_TB TO ROL_CONSULTA;
GRANT SELECT ON ADMIN_ARALIAS.FIDE_HORARIOS_TURNOS_TB TO ROL_CONSULTA;
GRANT SELECT ON ADMIN_ARALIAS.FIDE_FECHAS_TURNOS_TB TO ROL_CONSULTA;
GRANT SELECT ON ADMIN_ARALIAS.FIDE_TIPOS_ESPACIOS_TB TO ROL_CONSULTA;
GRANT SELECT ON ADMIN_ARALIAS.FIDE_TIPOS_EVENTOS_TB TO ROL_CONSULTA;
GRANT SELECT ON ADMIN_ARALIAS.FIDE_TIPOS_SERVICIOS_TB TO ROL_CONSULTA;
GRANT SELECT ON ADMIN_ARALIAS.FIDE_PERSONAS_TB  TO ROL_CONSULTA;
GRANT SELECT ON ADMIN_ARALIAS.FIDE_TELEFONOS_TB TO ROL_CONSULTA;
GRANT SELECT ON ADMIN_ARALIAS.FIDE_CORREOS_TB TO ROL_CONSULTA;
GRANT SELECT ON ADMIN_ARALIAS.FIDE_RESIDENCIAS_TB TO ROL_CONSULTA;
GRANT SELECT ON ADMIN_ARALIAS.FIDE_RESIDENTES_TB TO ROL_CONSULTA;
GRANT SELECT ON ADMIN_ARALIAS.FIDE_EVENTOS_TB TO ROL_CONSULTA;
GRANT SELECT ON ADMIN_ARALIAS.FIDE_VEHICULOS_TB TO ROL_CONSULTA;
GRANT SELECT ON ADMIN_ARALIAS.FIDE_SERVICIOS_TB TO ROL_CONSULTA;
GRANT SELECT ON ADMIN_ARALIAS.FIDE_FACTURAS_TB TO ROL_CONSULTA;
GRANT SELECT ON ADMIN_ARALIAS.FIDE_CONSULTAS_TB TO ROL_CONSULTA;
GRANT SELECT ON ADMIN_ARALIAS.FIDE_REPORTES_TB TO ROL_CONSULTA;
GRANT SELECT ON ADMIN_ARALIAS.FIDE_SALARIOS_TB TO ROL_CONSULTA;
GRANT SELECT ON ADMIN_ARALIAS.FIDE_PAQUETES_TB TO ROL_CONSULTA;
GRANT SELECT ON ADMIN_ARALIAS.FIDE_TURNOS_TB TO ROL_CONSULTA;
GRANT SELECT ON ADMIN_ARALIAS.FIDE_VISITAS_TB TO ROL_CONSULTA;
GRANT SELECT ON ADMIN_ARALIAS.FIDE_PERSONAS_SERVICIOS_TB TO ROL_CONSULTA;
GRANT SELECT ON ADMIN_ARALIAS.FIDE_RESUMENES_TURNOS_TB TO ROL_CONSULTA;
